//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UzsakymuValdymoSistema.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UzsakymuValdymoSistema.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientId,ClientName,ClientCompanyName
        ///1,Jonas,UAB Lydimo darbai
        ///2,Petras,UAB China Trade
        ///3,Andrius,UAB Smeltlita
        ///4,Jonas,UAB Gelezinis
        ///5,Tomas,UAB Ores
        ///6,Juozas,UAB JuozukoLankai
        ///.
        /// </summary>
        internal static string ClientRepository {
            get {
                return ResourceManager.GetString("ClientRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderId,ClinetId,ClientName,ClientCompany,ProductId,ProductName,Ammount,TotalPrice
        ///1,1,Jonas,UAB Lydimo darbai,1,Copper,20,1791,2
        ///2,2,Petras,UAB China Trade,2,Iron,10,1420
        ///3,3,Andrius,UAB Smeltlita,3,Coal,40,2760
        ///4,4,Jonas,UAB Gelezinis,4,Tin,50,2500
        ///5,3,Andrius,UAB Smeltlita,5,Sulfur,60,9600
        ///6,2,Petras,UAB China Trade,4,Tin,12,600
        ///7,1,Jonas,UAB Lydimo darbai,5,Sulfur,45,7200
        ///8,4,Jonas,UAB Gelezinis,1,Copper,13,1164,28
        ///9,3,Andrius,UAB Smeltlita,3,Coal,10,690
        ///10,1,Jonas,UAB Lydimo darbai,2,Iron,8,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OrdersReport {
            get {
                return ResourceManager.GetString("OrdersReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderId,ClientId,ProductId,Ammount
        ///1,1,1,20
        ///2,2,2,10
        ///3,3,3,40
        ///4,4,4,50
        ///5,3,5,60
        ///6,2,4,12
        ///7,1,5,45
        ///8,4,1,13
        ///9,3,3,10
        ///10,1,2,8
        ///11,3,4,300
        ///.
        /// </summary>
        internal static string OrdersRepository {
            get {
                return ResourceManager.GetString("OrdersRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductId,ProductName,Price
        ///1,Copper,89
        ///2,Iron,142
        ///3,Coal,69
        ///4,Tin,50
        ///5,Sulfur,160
        ///.
        /// </summary>
        internal static string ProductRepository {
            get {
                return ResourceManager.GetString("ProductRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
    }
}
